id = "mql"
name = "MQL"
description = "MQL5 (MetaQuotes Language) support for MetaTrader 5 with hover docs, code completion, and go-to-definition."
version = "0.1.2"
schema_version = 1
authors = ["rith sila <khmertools7@gmail.com>"]
repository = "https://github.com/rithsila/mql-for-zed"

[grammars.cpp]
repository = "https://github.com/tree-sitter/tree-sitter-cpp"
rev = "c009222808634c1014f82438d4883753516a2c24"

[grammars.ini]
repository = "https://github.com/justinmk/tree-sitter-ini"
rev = "e4018b5176132b4f3c5d6e61cea383f42288d0f5"

[lib]
kind = "Rust"

[language_servers.mql-lsp]
name = "MQL Language Server"
languages = ["MQL", "MQL Set"]
