#!/usr/bin/env python3
"""Generate a Strategy Tester .set file from the literal `input` defaults in an .mq5 (and its quoted local includes).
Inputs whose default is not a plain literal (enums, expressions, macros, colors, datetimes) are left out, so the tester
uses the EA's compiled default for them. Usage: gen-set.py <file.mq5> <out.set>"""
import os
import re
import sys

INT = {"int", "uint", "long", "ulong", "short", "ushort", "char", "uchar"}
FLT = {"double", "float"}
BUILTIN = {
    "PERIOD_CURRENT": 0, "PERIOD_M1": 1, "PERIOD_M2": 2, "PERIOD_M3": 3, "PERIOD_M4": 4, "PERIOD_M5": 5, "PERIOD_M6": 6,
    "PERIOD_M10": 10, "PERIOD_M12": 12, "PERIOD_M15": 15, "PERIOD_M20": 20, "PERIOD_M30": 30, "PERIOD_H1": 16385,
    "PERIOD_H2": 16386, "PERIOD_H3": 16387, "PERIOD_H4": 16388, "PERIOD_H6": 16390, "PERIOD_H8": 16392,
    "PERIOD_H12": 16396, "PERIOD_D1": 16408, "PERIOD_W1": 32769, "PERIOD_MN1": 49153,
    "MODE_SMA": 0, "MODE_EMA": 1, "MODE_SMMA": 2, "MODE_LWMA": 3,
    "PRICE_CLOSE": 1, "PRICE_OPEN": 2, "PRICE_HIGH": 3, "PRICE_LOW": 4, "PRICE_MEDIAN": 5, "PRICE_TYPICAL": 6, "PRICE_WEIGHTED": 7,
    "ORDER_FILLING_FOK": 0, "ORDER_FILLING_IOC": 1, "ORDER_FILLING_RETURN": 2,
}
DECL = re.compile(r"^\s*s?input\s+(?!group\b)(?P<type>[A-Za-z_][\w ]*?)\s+(?P<name>[A-Za-z_]\w*)\s*=\s*(?P<rest>.*)$")


def strip_comment_and_semicolon(rest):
    out, q, i = [], False, 0
    while i < len(rest):
        c = rest[i]
        if q:
            out.append(c)
            if c == "\\" and i + 1 < len(rest):
                out.append(rest[i + 1]); i += 1
            elif c == '"':
                q = False
        elif c == '"':
            q = True; out.append(c)
        elif c == ";" or rest.startswith("//", i):
            break
        else:
            out.append(c)
        i += 1
    return "".join(out).strip()


def enum_values(text):
    """Integer value of every member of every `enum X { ... }` in the source, plus a few common built-in enums."""
    vals = dict(BUILTIN)
    text = re.sub(r"//[^\n]*|/\*.*?\*/", "", text, flags=re.S)
    for body in re.findall(r"\benum\s+\w+\s*\{(.*?)\}", text, re.S):
        nxt = 0
        for item in (i.strip() for i in body.split(",")):
            if not item:
                continue
            name, _, expr = (x.strip() for x in item.partition("="))
            if expr:
                m = re.fullmatch(r"([-+]?(?:0[xX][0-9a-fA-F]+|\d+)|[A-Za-z_]\w*)(?:\s*([-+])\s*(\d+))?", expr)
                if not m:
                    nxt = None
                    continue
                base = int(m[1], 0) if re.match(r"[-+]?\d", m[1]) else vals.get(m[1])
                nxt = None if base is None else base + (int(m[3]) * (1 if m[2] != "-" else -1) if m[2] else 0)
            if nxt is None:
                continue
            vals[name] = nxt
            nxt += 1
    return vals


def literal(typ, v, enums=None):
    t = typ.replace("unsigned ", "u").strip()
    if t == "bool":
        return {"true": "true", "false": "false", "0": "false", "1": "true"}.get(v)
    if t == "string":
        return v[1:-1].replace('\\"', '"').replace("\\\\", "\\") if re.fullmatch(r'"(?:[^"\\]|\\.)*"', v) else None
    if t in INT:
        return str(int(v, 0)) if re.fullmatch(r"[-+]?(0[xX][0-9a-fA-F]+|\d+)", v) else None
    if t in FLT:
        m = re.fullmatch(r"([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)[fF]?", v)
        return m.group(1) if m else None
    if enums and v in enums and t not in ("string", "bool"):
        return str(enums[v])
    return None


def read(path, seen):
    path = os.path.abspath(path)
    if path in seen or not os.path.isfile(path):
        return ""
    seen.add(path)
    text = open(path, encoding="utf-8", errors="replace").read()
    for inc in re.findall(r'^\s*#include\s+"([^"]+)"', text, re.M):
        text += "\n" + read(os.path.join(os.path.dirname(path), inc.replace("\\", "/")), seen)
    return text


def main():
    src, out = sys.argv[1], sys.argv[2]
    lines, skipped = [], []
    text = read(src, set())
    enums = enum_values(text)
    for line in text.splitlines():
        m = DECL.match(line)
        if not m:
            continue
        val = literal(m["type"], strip_comment_and_semicolon(m["rest"]), enums)
        (lines if val is not None else skipped).append(f"{m['name']}={val}" if val is not None else m["name"])
    with open(out, "w", newline="") as f:
        f.write(f"; generated by zed-mql from {os.path.basename(src)}: literal input defaults. Delete this line to keep your edits.\r\n")
        if skipped:
            f.write("; not literal, the EA's compiled default applies: " + ", ".join(skipped) + "\r\n")
        f.write("\r\n".join(lines) + "\r\n")
    print(f"{len(lines)} inputs written, {len(skipped)} left to the EA default" + (f" ({', '.join(skipped[:6])}{', ...' if len(skipped) > 6 else ''})" if skipped else ""))


if __name__ == "__main__":
    main()
