#!/usr/bin/env python3
"""Generate a Strategy Tester .set file from the literal `input` defaults in an .mq5 (and its quoted local includes).
Inputs whose default is not a plain literal (enums, expressions, macros, colors, datetimes) are left out, so the tester
uses the EA's compiled default for them. Usage: gen-set.py <file.mq5> <out.set>"""
import os
import re
import sys

INT = {"int", "uint", "long", "ulong", "short", "ushort", "char", "uchar"}
FLT = {"double", "float"}
DECL = re.compile(r"^\s*s?input\s+(?!group\b)(?P<type>[A-Za-z_][\w ]*?)\s+(?P<name>[A-Za-z_]\w*)\s*=\s*(?P<rest>.*)$")


def strip_comment_and_semicolon(rest):
    out, q, i = [], False, 0
    while i < len(rest):
        c = rest[i]
        if q:
            out.append(c)
            if c == "\\" and i + 1 < len(rest):
                out.append(rest[i + 1]); i += 1
            elif c == '"':
                q = False
        elif c == '"':
            q = True; out.append(c)
        elif c == ";" or rest.startswith("//", i):
            break
        else:
            out.append(c)
        i += 1
    return "".join(out).strip()


def literal(typ, v):
    t = typ.replace("unsigned ", "u").strip()
    if t == "bool":
        return {"true": "true", "false": "false", "0": "false", "1": "true"}.get(v)
    if t == "string":
        return v[1:-1].replace('\\"', '"').replace("\\\\", "\\") if re.fullmatch(r'"(?:[^"\\]|\\.)*"', v) else None
    if t in INT:
        return str(int(v, 0)) if re.fullmatch(r"[-+]?(0[xX][0-9a-fA-F]+|\d+)", v) else None
    if t in FLT:
        m = re.fullmatch(r"([-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?)[fF]?", v)
        return m.group(1) if m else None
    return None


def read(path, seen):
    path = os.path.abspath(path)
    if path in seen or not os.path.isfile(path):
        return ""
    seen.add(path)
    text = open(path, encoding="utf-8", errors="replace").read()
    for inc in re.findall(r'^\s*#include\s+"([^"]+)"', text, re.M):
        text += "\n" + read(os.path.join(os.path.dirname(path), inc.replace("\\", "/")), seen)
    return text


def main():
    src, out = sys.argv[1], sys.argv[2]
    lines, skipped = [], []
    for line in read(src, set()).splitlines():
        m = DECL.match(line)
        if not m:
            continue
        val = literal(m["type"], strip_comment_and_semicolon(m["rest"]))
        (lines if val is not None else skipped).append(f"{m['name']}={val}" if val is not None else m["name"])
    with open(out, "w", newline="") as f:
        f.write(f"; generated by zed-mql from {os.path.basename(src)}: literal input defaults. Delete this line to keep your edits.\r\n")
        if skipped:
            f.write("; not literal, the EA's compiled default applies: " + ", ".join(skipped) + "\r\n")
        f.write("\r\n".join(lines) + "\r\n")
    print(f"{len(lines)} inputs written, {len(skipped)} left to the EA default" + (f" ({', '.join(skipped[:6])}{', ...' if len(skipped) > 6 else ''})" if skipped else ""))


if __name__ == "__main__":
    main()
