#!/usr/bin/env python3
"""Summarise one MT5 Strategy Tester run from the terminal log and tester log (only the bytes written during the run)."""
import argparse
import csv
import html
import json
import os
import re
import sys
from datetime import datetime, timezone


def segment(path, offset):
    try:
        with open(path, "rb") as f:
            head = f.read(200)
            wide = b"\x00" in head
            f.seek(offset - offset % 2 if wide else offset)
            data = f.read()
    except OSError:
        return []
    return data.decode("utf-16-le" if wide else "utf-8", "replace").splitlines()


def message(line):
    parts = line.split("\t")
    return parts[-1].strip() if len(parts) >= 5 else line.strip()


def load_deals(path):
    rows = []
    try:
        with open(path, newline="", encoding="utf-8", errors="replace") as f:
            for r in csv.DictReader(f):
                rows.append({"t": int(r["time"]), "type": int(r["type"]), "entry": int(r["entry"]), "symbol": r["symbol"],
                             "net": sum(float(r[k]) for k in ("profit", "swap", "commission", "fee"))})
    except (OSError, ValueError, KeyError):
        return []
    return rows


def write_report(path, title, info, deals, cur, stats):
    bal, curve = 0.0, []
    for d in deals:
        bal += d["net"]
        curve.append((d["t"], bal))
    closing = [d["net"] for d in deals if d["type"] in (0, 1) and d["entry"] in (1, 2, 3)]
    wins = [x for x in closing if x > 0]
    losses = [x for x in closing if x < 0]
    peak, mdd, mdd_pct = curve[0][1], 0.0, 0.0
    for _, b in curve:
        peak = max(peak, b)
        mdd = max(mdd, peak - b)
        mdd_pct = max(mdd_pct, (peak - b) / peak * 100 if peak > 0 else 0)
    step = max(1, len(curve) // 1500)
    pts = curve[::step] + ([curve[-1]] if (len(curve) - 1) % step else [])
    lo, hi = min(b for _, b in pts), max(b for _, b in pts)
    t0, t1 = pts[0][0], pts[-1][0]
    W, H, L, B = 900, 280, 70, 30
    xs = lambda t: L + (t - t0) / max(1, t1 - t0) * (W - L - 10)
    ys = lambda b: 10 + (hi - b) / max(1e-9, hi - lo) * (H - B - 10)
    poly = " ".join(f"{xs(t):.1f},{ys(b):.1f}" for t, b in pts)
    day = lambda t: datetime.fromtimestamp(t, timezone.utc).strftime("%Y-%m-%d")
    def kpi(rows):
        return "".join(f"<tr><th>{html.escape(k)}</th><td>{html.escape(str(v))}</td></tr>" for k, v in rows)
    g = lambda k: float(stats.get(k, "nan")) if stats else float("nan")
    tester = [("Profit factor", f"{g('profit_factor'):.2f}"), ("Net profit", f"{g('profit'):.2f} {cur}"),
              ("Gross profit / loss", f"{g('gross_profit'):.2f} / {g('gross_loss'):.2f}"),
              ("Equity drawdown", f"{g('equity_dd'):.2f} {cur} ({g('equity_dd_pct'):.2f}%)"),
              ("Recovery factor", f"{g('recovery_factor'):.2f}"), ("Sharpe", f"{g('sharpe'):.2f}"),
              ("Expected payoff", f"{g('expected_payoff'):.2f}"), ("Trades (tester)", f"{g('trades'):.0f}")] if stats else []
    own = [("Closing deals", len(closing)),
           ("Win rate", f"{len(wins) / len(closing) * 100:.1f}%" if closing else "n/a"),
           ("Average win / loss", f"{sum(wins) / len(wins):.2f} / {sum(losses) / len(losses):.2f}" if wins and losses else "n/a"),
           ("Largest win / loss", f"{max(wins):.2f} / {min(losses):.2f}" if wins and losses else "n/a"),
           ("Balance drawdown (closed deals)", f"{mdd:.2f} {cur} ({mdd_pct:.2f}%)"),
           ("Final balance", f"{curve[-1][1]:.2f} {cur}")]
    doc = f"""<!doctype html><meta charset="utf-8"><title>{html.escape(title)}</title>
<style>body{{font:14px system-ui,sans-serif;margin:24px;max-width:960px;color:#222}}h1{{font-size:20px}}table{{border-collapse:collapse;margin:8px 24px 8px 0}}
th{{text-align:left;font-weight:500;padding:3px 14px 3px 0;color:#555}}td{{padding:3px 0;font-variant-numeric:tabular-nums}}.row{{display:flex;flex-wrap:wrap}}svg{{background:#fafafa;border:1px solid #ddd}}small{{color:#777}}</style>
<h1>{html.escape(title)}</h1><p>{html.escape(info)}</p>
<div class="row"><table>{kpi(tester)}</table><table>{kpi(own)}</table></div>
<h2 style="font-size:16px">Balance curve</h2>
<svg width="{W}" height="{H}"><polyline fill="none" stroke="#1565c0" stroke-width="1.4" points="{poly}"/>
<text x="4" y="18" font-size="11">{hi:.0f}</text><text x="4" y="{H - B}" font-size="11">{lo:.0f}</text>
<text x="{L}" y="{H - 10}" font-size="11">{day(t0)}</text><text x="{W - 80}" y="{H - 10}" font-size="11">{day(t1)}</text></svg>
<p><small>Balance after each deal (not equity; floating P/L is not sampled). Statistics on the left come from the tester's own TesterStatistics(); the right column is computed from the deal list. Generated by zed-mql. Strategy Tester results are not a prediction of live performance.</small></p>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--terminal-log", required=True)
    ap.add_argument("--terminal-offset", type=int, default=0)
    ap.add_argument("--tester-log", required=True)
    ap.add_argument("--tester-offset", type=int, default=0)
    ap.add_argument("--deposit", type=float, default=0)
    ap.add_argument("--currency", default="")
    ap.add_argument("--save-tester-segment")
    ap.add_argument("--deals-csv")
    ap.add_argument("--report-html")
    ap.add_argument("--run-dir")
    ap.add_argument("--title", default="Strategy Tester")
    ap.add_argument("--info", default="")
    a = ap.parse_args()

    term = [message(l) for l in segment(a.terminal_log, a.terminal_offset)]
    raw_test = segment(a.tester_log, a.tester_offset)
    if a.save_tester_segment:
        with open(a.save_tester_segment, "w") as f:
            f.write("\n".join(raw_test) + "\n")
    test = [message(l) for l in raw_test]

    for m in term:
        if re.search(r"tester (not started|didn't start)|tester .*does not exist|account is not specified|shutdown with -", m, re.I):
            print(f"FAIL: {m}")
    failed = [m for m in term if re.search(r"tester (not started|didn't start)", m, re.I)]
    if failed:
        if a.run_dir:
            with open(os.path.join(a.run_dir, "result.json"), "w") as f:
                json.dump({"schema_version": 1, "status": "failed", "error": "tester did not start"}, f, indent=2)
        return 1

    final = [re.search(r"final balance\s+([-\d.]+)\s*(\w*)", m) for m in test]
    final = [m for m in final if m]
    finished = [m for m in term if "last test passed" in m or "last test failed" in m]
    if not final:
        err = "no 'final balance' in tester log" + (f" ({finished[-1]})" if finished else " (tester did not run)")
        print(f"FAIL: {err}")
        for m in [m for m in test if re.search(r"error|fail|cannot|not found|critical", m, re.I)][-8:]:
            print(f"  {m}")
        if a.run_dir:
            with open(os.path.join(a.run_dir, "result.json"), "w") as f:
                json.dump({"schema_version": 1, "status": "failed", "error": err}, f, indent=2)
        return 1

    bal = float(final[-1].group(1))
    cur = final[-1].group(2) or a.currency
    deals = sum(1 for m in test if re.search(r"\bdeal #\d+ (buy|sell) .* done", m))
    ontester = next((m.split("result")[-1].strip() for m in reversed(test) if m.startswith("OnTester result")), None)
    took = next((re.search(r"Test passed in (\S+)", m).group(1) for m in reversed(test) if re.search(r"Test passed in \S+", m)), None)
    mem = next((m for m in reversed(test) if re.search(r"ticks.*bars generated", m)), None)

    print("---- Strategy Tester summary ----")
    if a.deposit:
        net = bal - a.deposit
        print(f"Deposit       : {a.deposit:.2f} {cur}")
        print(f"Final balance : {bal:.2f} {cur}  (net {net:+.2f}, {net / a.deposit * 100:+.2f}%)")
    else:
        print(f"Final balance : {bal:.2f} {cur}")
    print(f"Deals         : {deals}")
    if ontester:
        print(f"OnTester      : {ontester}")
    if took:
        print(f"Test time     : {took.rstrip('.')}")
    if mem:
        print(f"Data          : {mem.split(': ', 1)[-1].split('. ')[0]}")
    stats = next((dict(kv.split("=", 1) for kv in re.search(r"ZEDMQL_STATS (.*)", m).group(1).split() if "=" in kv)
                  for m in reversed(test) if "ZEDMQL_STATS " in m), None)
    
    result_json = {
        "schema_version": 1,
        "status": "success",
        "metrics": {
            "final_balance": {"value": bal, "provenance": "native"},
            "deals": {"value": deals, "provenance": "native"}
        },
        "unavailable_metrics": {}
    }
    if a.deposit:
        result_json["metrics"]["net_profit"] = {"value": bal - a.deposit, "provenance": "native"}

    if stats:
        g = lambda k: float(stats.get(k, "nan"))
        result_json["metrics"].update({
            "trades": {"value": int(g('trades')), "provenance": "native"},
            "profit_factor": {"value": g('profit_factor'), "provenance": "native"},
            "gross_profit": {"value": g('gross_profit'), "provenance": "native"},
            "gross_loss": {"value": g('gross_loss'), "provenance": "native"},
            "equity_dd": {"value": g('equity_dd'), "provenance": "native"},
            "equity_dd_pct": {"value": g('equity_dd_pct'), "provenance": "native"},
            "recovery_factor": {"value": g('recovery_factor'), "provenance": "native"},
            "sharpe": {"value": g('sharpe'), "provenance": "native"},
            "expected_payoff": {"value": g('expected_payoff'), "provenance": "native"}
        })
        print(f"Trades        : {int(g('trades'))}")
        print(f"Profit factor : {g('profit_factor'):.2f}   (gross +{g('gross_profit'):.2f} / {g('gross_loss'):.2f})")
        print(f"Equity DD     : {g('equity_dd'):.2f} {cur}  ({g('equity_dd_pct'):.2f}%)")
        print(f"Recovery      : {g('recovery_factor'):.2f}   Sharpe {g('sharpe'):.2f}   Expected payoff {g('expected_payoff'):.2f}")
        deal_list = load_deals(a.deals_csv) if a.deals_csv else []
        if deal_list and a.report_html:
            write_report(a.report_html, a.title, a.info, deal_list, cur, stats)
            print(f"Report        : {a.report_html}")
        elif a.report_html:
            print("Report        : not written (no deal list; update ZedMqlStats.mqh in the EA's include and rebuild)")
    else:
        reason = "not available; add ZedMqlStats.mqh to the EA's OnTester"
        result_json["unavailable_metrics"] = {
            "trades": reason, "profit_factor": reason, "gross_profit": reason,
            "gross_loss": reason, "equity_dd": reason, "equity_dd_pct": reason,
            "recovery_factor": reason, "sharpe": reason, "expected_payoff": reason
        }
        print(f"Drawdown / PF : {reason}")

    if a.run_dir:
        with open(os.path.join(a.run_dir, "result.json"), "w") as f:
            json.dump(result_json, f, indent=2)

    return 0


if __name__ == "__main__":
    sys.exit(main())
